const AUTH_KEY = import.meta.env.VITE_CLERK_PUBLISHABLE_KEY;
const API_KEY = import.meta.env.VITE_STRAPI_API_KEY;
const GEMENI_API_KEY = import.meta.env.VITE_GEMENI_API_KEY;
const VITE_APP_URL = import.meta.env.VITE_APP_URL;
const VITE_PUBLIC_URL = import.meta.env.VITE_PUBLIC_URL;
const VITE_GOOGLE_CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID; // <-- ADD THIS

export { AUTH_KEY, API_KEY, VITE_PUBLIC_URL, GEMENI_API_KEY,VITE_APP_URL, VITE_GOOGLE_CLIENT_ID }; // <-- ADD VITE_GOOGLE_CLIENT_ID
