export const queryKeys = {
  auth: {
    all: ["auth"],
    session: ["auth", "session-user"],
    profile: ["auth", "profile"],
    notifications: ["auth", "notification-preferences"],
  },
  admin: {
    all: ["admin"],
    session: ["admin", "session"],
    dashboard: (days) => ["admin", "dashboard", days],
    accounts: ["admin", "accounts"],
    users: (params = {}) => ["admin", "users", params],
    usersLite: ["admin", "users-lite"],
    userDetail: (userId) => ["admin", "user-detail", userId],
    resumes: (params = {}) => ["admin", "resumes", params],
    resumesByUser: (userId) => ["admin", "resumes-by-user", userId],
    coverLetters: (params = {}) => ["admin", "cover-letters", params],
    invites: ["admin", "external-invites"],
    inviteDetail: (inviteId) => ["admin", "external-invite-detail", inviteId],
    externalUsers: ["admin", "external-users"],
    notifications: (params = {}) => ["admin", "notifications", params],
    studentIds: ["admin", "student-ids"],
  },
  resumes: {
    all: ["resumes"],
    list: ["resumes", "list"],
    detail: (resumeId) => ["resumes", "detail", resumeId],
  },
};
